### PR TITLE
feat(ng-cli): introduce ng-cli build and fixing https://github.com/an…

### LINKED ISSUE #381: Deprecate tree list
Deprecate the tree-list component in anticipation of Angular 6 support. This decision was made due to additional issues with mobx autorun introduced by angular-tree-component.

If angular-tree-component resolves the issue below, it's possible we could reintroduce the tree-list component. However, this particular issue should not prevent patternfly-ng from supporting Angular 6.

See: 500tech/angular-tree-component#596

### PR DESCRIPTION
**Pull request by corinnekrych**
…gular/angular-cli/issues/10615 issue

Hello @dlabrecq ,

This is a proposal to fix: https://github.com/patternfly/patternfly-ng/issues/381
which was linked to https://github.com/500tech/angular-tree-component/issues/596

Refactoring patternfly-sandbox-ng to use ng-cli6 build, I've bumped into a similar issue https://github.com/angular/angular-cli/issues/10615 on AOT build. I've followed the instructions, move to `"ng-packagr": "^4.1.1"` and tune the `ngc` with the options in `tsconfig.lib.json`.

You can now build the library and the demo app with OAT. I've also tested with an external app, doing a `npm run package` and using the tgz. See repo here: https://github.com/corinnekrych/patternfly-sandbox-ng-app/blob/master/README.md

### CODE REVIEW

**Comment by corinnekrych** [comment]
@dlabrecq do you mind a review?

**Comment by dlabrecq** [comment]
This is quite a large change for a single component. It may be helpful to walk through this offline?

Ideally, this would be fixed by the angular-tree-component package. I was hoping we could then bring the tree-list component back into patternfly-ng after the issue is addressed.

I'm not necessarily opposed to these changes, but it may have significant implications for a sandbox repo. For example, it's not clear if we should use this build infrastructure for future component contributions?

After these changes, this repo probably cannot be considered a sandbox for patternfly-ng? The idea was to have an identical repo infrastructure in order to move components and examples from this repo to patetrnfly-ng with little or no change.

If we need a specific build infrastructure for tree-list, I'm thinking we should rename the repo from patternfly-ng-sandbox to patternfly-ng-tree-list. Or, create a new patternfly-ng-tree-list repo based on these changes?

That said, I ran into some issues attempting to build and test with the new infrastructure. The build seemed to hang for a while and then output the error below.

build:
```
ERROR in multi ./node_modules/patternfly/dist/css/patternfly.min.css ./node_modules/patternfly/dist/css/patternfly-additions.min.css ./node_modules/patternfly-ng/dist/css/patternfly-ng.min.css ./src/styles.css

Date: 2018-09-13T14:02:01.947Z
Module not found: Error: Can't resolve '/Users/dlabrecq/Work/patternfly/repos/patternfly-sandbox-ng-tests/patternfly-sandbox-ng/src/styles.css' in '/Users/dlabrecq/Work/patternfly/repos/patternfly-sandbox-ng-tests/patternfly-sandbox-ng'
```

test:
```
13 09 2018 09:58:06.651:ERROR [launcher]: Cannot load browser "ChromeHeadlessNoSandbox": it is not registered! Perhaps you are missing some plugin?
13 09 2018 09:58:06.651:ERROR [karma]: Found 1 load error
```

**Comment by dlabrecq** [comment]
I was able to build your sandbox and demo app. However, I noticed this repo build only generates a umd bundle and doesn't provide any index.js files for es6 module imports. The CSS files also appear to be missing.

Under the dist directory, I see patternfly-sandbox-ng and patternfly-sandbox-ng-demo, which is a very different structure than what we delivered previously. A little deeper, I found a umd bundle (esm2015) file. I also found an fesm bundle, but not clear why that is being delivered? 

For patternfly-ng, we recently added a umd bundle to support SystemJS apps -- OS.io doesn't use that. Your changes appear to build a similar bundle, but in a different way (i.e., using ng-cli Vs rollup). Although the bundles should be similar, the main difference is that existing patternfly-ng packages also include index.js files for individual es6 module imports.

Note that the patternfly-ng packages are intended to be used similar to ngx-bootstrap. That is, so apps can import modules individually without also having to build unused components and dependencies, like dragula, ngx-datatable, etc. This greatly speeds up the build (I changed OS.io to make use of this) and helps with tree shaking. 

I should be able to import an individual module by referencing the index.js file in each sub-directory, like so:

`import { TreeListModule } from 'patternfly-sandbox-ng/tree-list'`

When testing your bundle in my own app, angular-tree-component compiled with AOT. However, I suspect this works here because all of the package dependencies are already bundled, so AOT has what it needs to build the app.

We still need to generate a bundle, but probably shouldn't be the only option. Otherwise, apps may not be able to omit unused components and dependencies from the build. And you probably couldn't install your own angular-tree-component package, for example.

That said, it's not clear if the underlying issue is related to the build options used with ngc Vs ng-cli? Could it be that you're not building the index.js files used for individual es6 module imports? I'd like to better understand why the patternfly-ng AOT test fails.

**Comment by corinnekrych** [comment]
@dlabrecq to answer your question:
- css is inline (see my last commit 1eee3fa)
- about the format of the lib. ng-cli uses `ng-packagr` which follows [angular lib format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview# )  so it should fit systemJS too. Do you have a sample app to test systemjs ?
- individual import: i'm still looking here, I've put back the different index.js but still coulcn't use import { TreeListModule } from 'patternfly-sandbox-ng/list' in the demo. I'm still looking for this last point.

**Comment by dlabrecq** [comment]
I did some experimenting with the patternfly-ng repo and tree-list. I found that we can build angular-tree-component v8.0.0 and Angular v6.1.0, but without running tsconfig-aot.json as part of the build. 

Note that the tsconfig-aot.json file is run as an additional patternfly-ng build. However, it's only purpose is to help us catch potential AOT errors when creating new components. We had been using AngularCompilerPlugin while running the demo, but that's not currently compatible with Angular 6, so it was temporarily disabled.

That said, I propose that we keep the build infrastructure as is for the patternfly-sandbox-ng repo, but bump the version of angular and angular-tree-component and continue to mimic the patternfly-ng build. The only caveat is that we do not run the AOT test as part of the build. We're not currently running it in patternfly-sandbox-ng, so no changes here.

I believe this will accomplish what this PR is attempting to achieve? As long as we test that an angular-cli app can be created and built with AOT.

I would still prefer that we add an AOT during build time to catch potential errors. Ideally, we should figure out why tsconfig-aot.json does not work with angular-tree-component.

**Comment by corinnekrych** [comment]
@dlabrecq go ahead and close my PR to do it with as you suggested. keeping same build structure and cleaning aot build. I like my build better but 🤷‍♀️ you're the library owner.

**Pull request closed without merging**
